version: '3.8'

services:
  distributivo-frontend:
    image: distributivo-frontend:prod
    command: -c /distributivo/nginx/nginx
    networks:
      - distributivo_net
      - traefik-public
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 2024M      
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.horarios.entrypoints=http"
        - "traefik.http.routers.horarios.rule=Host(`horarios.yavirac.edu.ec`)"
        - "traefik.http.middlewares.horarios-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.horarios.middlewares=horarios-https-redirect"
        - "traefik.http.routers.horarios-secure.entrypoints=https"
        - "traefik.http.routers.horarios-secure.rule=Host(`horarios.yavirac.edu.ec`)"
        - "traefik.http.routers.horarios-secure.tls=true"
        - "traefik.http.routers.horarios-secure.tls.certresolver=http"
        - "traefik.http.routers.horarios-secure.service=horarios"
        - "traefik.http.services.horarios.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"   
networks:
  distributivo_net:
    external: true
  traefik-public:
    external: true
